### ISSUE TITLE
Improve file modification percentage bar

### ISSUE THREAD

**Issue by Tom-Bonnike** [brunosimon/keppler#15]
Maybe by switching it for a “+ n lines /- n lines”, like Github does?
![capture d ecran 2017-02-28 a 12 01 44](https://cloud.githubusercontent.com/assets/9154236/23402858/b33c406e-fdad-11e6-9c42-3d9ee8c2b4c5.png)

**Comment by brunosimon** [comment]
Maybe without the squares. They are not really clear.

**Comment by axelchalon** [comment]
The squares let us know how much of the file has changed. For example, if everything was replaced inside a file, all the squares would be filled. If half the file changed, half the squares would be filled; that's the main idea. I don't know think this is necessary but it helps the user see more quickly which modifications were the most important. Otherwise, the user would need to read the numbers (slower process) and compare them or figure out which ones are "big numbers".

It would look something like this:

![image](https://cloud.githubusercontent.com/assets/5739676/24401938/ba666b0c-13b6-11e7-83cd-7a03ae2400cd.png)

![image](https://cloud.githubusercontent.com/assets/5739676/24402131/855554ae-13b7-11e7-91fd-200b2f2ee7c9.png)

When the mouse is over the squares or the numbers ("+5 -2"), a tooltip could explain more clearly what the numbers and the squares mean. Also possible: "5 lines added, 2 lines removed ; 90% changes"

**Comment by Tom-Bonnike** [comment]
Now that I think about it again, I like the squares as they make more sense to me than the current “bar”. Having another quick “visual” way to check how much the file has changed (not only the +/-) could be useful, but I don’t think they’re 100% necessary. ¯\_(ツ)_/¯
