### ISSUE TITLE
Support of TypeScript

### ISSUE THREAD

**Issue by khylias** [brunosimon/keppler#38]
Hi,

this project is a very good idea and I think I can use it in my Angular course at the university. However, Keppler does not seem to support languages like TypeScript. 

Any list or plans about supported languages ?

Thanks for your work ! 👍

**Comment by brunosimon** [comment]
Hello,

That's a mistake. I'll try to fix that shortly.
When do you need it?

**Comment by khylias** [comment]
Thanks for quick answer. 

I'll start my course in few days this month, I understand that is a short deadline.

**Comment by brunosimon** [comment]
Here you go with the latest version.
Just run `sudo npm install -g keppler` to update keppler (but you probably already know).

The problem was that `.ts` files are considered by mime module as `video` and Keppler prevent the versionning of videos. I had to make an exception for `.ts` files. 

Thank you for the report.
In what university are you going to give that course? And for how many students? (just curious)

**Comment by khylias** [comment]
Awesome ! 
Thank you for this quick release and congratulations for this plugin 🙌 

I give the Angular course in La Rochelle, France for the Professional Licence in Web Development, I think you know La Rochelle because you are at HETIC Paris 😉My class has 17 students this year, my first teaching year.

**Comment by khylias** [comment]
I've got an issue on MimeType match on keppler's start : 

```
keppler/lib/watcher.js:162
            if(mimeType.match(/^(audio)|(video)|(image)/) && extension !== '.ts')
                        ^

TypeError: Cannot read property 'match' of null 
```

**Comment by brunosimon** [comment]
Oh,

I don't have this error with my testing files.
I can make a blind fix, but would you be able to find the file causing this error so I can make sure to fix it?
I don't think it's a Typescript.

**Comment by brunosimon** [comment]
Should be fixed.
